name: Pipeline


on:
  push:
    branches:
      - main



jobs:

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4 

      - name: connect and redeploy
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          sshpass -p '${{ secrets.VPS_PASSWORD }}' ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf ~/*"
          sshpass -p '${{ secrets.VPS_PASSWORD }}' scp -r ./web/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~

      - name: cleanup
        run: rm -rf ~/.ssh

